---
title: "Cyclistic 2019 Case-Study"
author: "Quintin Ramsey"
date: "11/28/2023"
# output: html_document
---

# Cyclistic Data 2019
A case-study on the bike-share data from the 'fictional' company Cyclistic


## The Case-Study
The data I have here is internal data from the Lyft's own database and has been made available by Motivate International Inc. See their [aggreement](https://divvybikes.com/data-license-agreement). The data is from Chicago in the year 2019. The data is split into quarterly segments, which have been combined later into one full-year dataset.

_"How do annual members and casual riders use Cyclistic bikes differently?"_

Right from the start, this is a very open ended question. I will need to use a programming language to be able to parse through all of that data very quickly.

## Looking at the Data
I should try to use R because of the sheer size of the datasets. However, R is not being very *cooperative* at the moment ...

Found the problem. It's a simple problem, really ... just change .md to a .Rmd file.
Oh... Pandoc ... Hold on a sec ...

```{R Importing Libraries}
# Import Libraries
library(tidyverse)
```


Okay Yayy! Kniting works! Now I can get cracking. I want an overview of the data that I will be looking at. The sheets might be different in some way, so it will be important to look at them seperately.


```{R Looking at the Data}
# Read in Q1
quarter_1 <- read_csv("Data\\Divvy_Trips_2019_Q1.csv")
```

As you can see, the spreadsheet is frikin HUGE!!! 365,069 different entries. However, R has been kind enough to identify date-times, and other datatypes automatically. Let's just check the other sheets to see if they can be merged together to create the whole year dataset.

```{R Looking at the Rest of the Data}
# Read in the other quarters
quarter_2 <- read_csv("Data\\Divvy_Trips_2019_Q2.csv")
quarter_3 <- read_csv("Data\\Divvy_Trips_2019_Q3.csv")
quarter_4 <- read_csv("Data\\Divvy_Trips_2019_Q4.csv")
```

Oh noooo! quarter_2 does not have the same column types as the rest. We will have to do some editing...

## Cleaning the Data
First off, those pesky column titles. The datatypes are all the same, but the column titles need renaming. Well, that should be an easy fix, just set the column names of quarter_2 to be the same as the column names from quarter_1:
```{R Changing Column Names}
# Q2 columns are in the same order as Q1, just different names
# Rename columns in Q2 to be the same as in Q1
colnames(quarter_2) <- colnames(quarter_1)
```
Now, I want to be able to see the whole year together as one single dataframe (of around 3 million or so entries). For that, I need to merge the frames. Because I want to preserve all of the data during the entire year, I cannot merge the data, I have to "union" the data. I can also only union two at a time, sooooo...

```{R Union}
# Join together all 4 quarter sheets into one full-year sheet
first_half <- union_all(quarter_1, quarter_2)
second_half <- union_all(quarter_3, quarter_4)
full_2019 <- union_all(first_half, second_half)
glimpse(full_2019)
```
Perfect! 12 columns, and every single row is accounted for. Let's see what we can find about our dataset.

## Who are These People?

### Gender
I want to get a quick plot of the gender of the rider for each ride in the dataset. Keep in mind, this may be rides by the same person, but we are looking at the data from the perspective of the rides, not the riders.
```{R View Gender Counts}
# View counts of each gender and usertype combination
gender_grouped <- full_2019 %>%
    group_by(gender, usertype) %>%
    summarize(gender_count = n())
gender_grouped
```
I will include the counts in the bar graph manually, as this is historical data not likely to change anytime soon ...
```{R Gender Bar}
# Plot a barplot of the data split by gender
ggplot(data = full_2019) +
    geom_bar(mapping = aes(x = gender, fill = usertype)) +
    annotate("text", x = 1, y = 726539 / 2, label = "726,539", size = 5) +
    annotate("text", x = 1, y = 726539 + (131439 / 2), label = "131,439", size = 5) +
    annotate("text", x = 2, y = 2188077 / 2, label = "2,188,077", size = 5) +
    annotate("text", x = 2, y = 2188077 + (212743 / 2), label = "212,743", size = 5) +
    annotate("text", x = 3, y = 22751 * 2, label = "22,751", size = 3) +
    annotate("text", x = 3, y = 22751 + (536455 / 2), label = "536,455", size = 5) +
    scale_y_continuous(labels = scales::comma) +
    xlab("Reported Gender") +
    ylab("Number of Riders") +
    labs(fill = "User Type", size = 12) +
    ggtitle("Number of Riders by Reported Gender and User Type")
```

We can also see what the split looks like the other way
```{R Subsriber Bar}
# Plot a barplot split by user type
ggplot(data = full_2019) +
    geom_bar(mapping = aes(x = usertype, fill = gender)) +
    annotate("text", x = 1, y = 536455 / 2, label = "536,455", size = 8) +
    annotate("text", x = 1, y = 536455 + (212743 / 2), label = "212,743", size = 7) +
    annotate("text", x = 1, y = 536455 + 212743 + (131439 / 2), label = "131,439", size = 3) +
    annotate("text", x = 2, y = 22751 * 2, label = "22,751", size = 5) +
    annotate("text", x = 2, y = 22751 + (2188077 / 2), label = "2,188,077", size = 8) +
    annotate("text", x = 2, y = 22751 + 2188077 + (726539 / 2), label = "726,539", size = 8) +
    scale_y_continuous(labels = scales::comma) +
    xlab("User Type") +
    ylab("Number of Riders") +
    labs(fill = "Reported Gender") +
    ggtitle("Number of Riders by User Type and Gender")
```


With the data we see here, a "Customer" is someone who is just purchasing a daily or weekly pass. A "Subscriber" is someone who has purchased the annual pass (or individual rides). From this, we can infer that people who purchase the membership are likely to report their gender. Additionally, we can clearly see that there are more men using the service than women. Most of the customers that use the serice, however, are members and purchase the annual membership. Likely, they inted to use the service year-round.

### Age
Setting some restrictions on the age of the riders might be important. Of all of the entries, 538,751 of them did not give an age. Furthermore, of those that did, some are set as young as 5 years old, while the oldest is a whopping 260 years old.
```{R Age}
# Take the difference between "now" (2019) and the birth year to get approx age.
full_2019$age_appx <- 2019 - full_2019$birthyear
filtered_age <- full_2019 %>%
    filter(age_appx != "NA")
min(filtered_age$age_appx)
max(filtered_age$age_appx)
```

Thus, we add some "reasonable" conditions before constructing the histogram.
```{R Age Filter}
# Filter for ages > 0 and < 100
filtered_age <- full_2019 %>%
    filter(age_appx < 100 & age_appx > 0 & age_appx != "NA")
```

Leaving 539,534 removed from the dataset (833 additional people older than 100), ages unlikely to be realistic for a bike-share program. Well ... Histogram, please ...

```{R Age Histogram}
# Plot a histogram of all rider ages
ggplot(data = filtered_age) +
    geom_histogram(mapping = aes(x = age_appx),
    fill = "#582a87", color = 'black', binwidth = 1, center = 0.5) + 
    annotate("text", x = 26.5, y = 210000, label = "Age: 26", size = 5) +
    scale_y_continuous(labels = scales::comma) +
    xlab("Approximate Age (2019 - Birth Year)") +
    ylab("Number of Riders") +
    ggtitle("Histogram of the Approximate Age of the Rider")
```

The most common ages are those of people in their older 20's. We can also quickly see what the data looks like split by user type and by gender.
```{R User Type Histogram}
# Plot a histogram of all rider ages split by user type
ggplot(data = filtered_age) +
    geom_histogram(mapping = aes(x = age_appx, fill = usertype),
    color = 'black', binwidth = 1, center = 0.5) + 
    facet_wrap(~usertype) + 
    scale_y_continuous(labels = scales::comma) +
    xlab("Approximate Age (2019 - Birth Year)") +
    ylab("Number of Riders") +
    labs(fill = "User Type") +
    ggtitle("Histogram of the Approximate Age of the Rider",
        subtitle = "Split by User Type")
```

Dropping an additional 20,412 people who cited their gender as "NA", we get:

```{R Gender Histogram}
# Drop NA gender
filtered_age <- filtered_age %>% filter(gender != "NA")

# Plot histogram of ages split by gender
ggplot(data = filtered_age) +
    geom_histogram(mapping = aes(x = age_appx, fill = gender),
    color = 'black', binwidth = 1, center = 0.5) +
    facet_wrap(~gender) +
    scale_y_continuous(labels = scales::comma) +
    xlab("Approximate Age (2019 - Birth Year)") +
    ylab("Number of Riders") +
    labs(fill = "Reported Gender") +
    ggtitle("Histogram of the Approximate Age of the Rider",
        subtitle = "Split by Gender")
```

***The data also demonstrate that the people who did not give reliable ages were also the people who tended not to include thier gender***

## Trends

### Annual
Because most of the rides were taken by annual subsribers, it might be helpful to see when the service is being most used, and by which group.
```{R Date Group}
# I need a new column so that I can group by date
full_2019$start_date <- as.Date(full_2019$start_time)

# As well as a few different data frames to plot
date_grouped <- full_2019 %>%
    group_by(start_date) %>%
    summarize(daily_rides = n())
date_grouped

# One for Customers Only
customer_rides <- full_2019 %>%
    filter(usertype == "Customer") %>%
    group_by(start_date) %>%
    summarize(daily_rides = n())
customer_rides

# And one for Subscribers Only
subscriber_rides <- full_2019 %>%
    filter(usertype == "Subscriber") %>%
    group_by(start_date) %>%
    summarize(daily_rides = n())
subscriber_rides
```
Good. 365 rows of data for each tibble, each with a count of daily rides. Let's plot all three as a line. I have to turn this into a long_table to plot all three lines together.

```{R Pivot Longer}
# Turn into long format to be used for line plot
to_pivot <- data.frame(date = date_grouped$start_date,
                      totals = date_grouped$daily_rides,
                      cust = customer_rides$daily_rides,
                      subs = subscriber_rides$daily_rides)
longer <- to_pivot %>% pivot_longer(cols = c("totals", "cust", "subs"),
                                    names_to = "usertype",
                                    values_to = "daily_rides")

# Plot a line plot showing all both types and total
ggplot(data = longer, aes(x = date, y = daily_rides)) +
    geom_line(aes(color = usertype)) +
    scale_color_manual(
            name = "User Type",
            labels = c("Customer", "Subscriber", "Total"),
            values = c("#F8766D", "#619CFF", "#000000")) +
    xlab("Ride Start Date") +
    scale_x_continuous(
        breaks = as.Date(
                 c("2019-01-01", "2019-02-01", "2019-03-01",
                   "2019-04-01", "2019-05-01", "2019-06-01",
                   "2019-07-01", "2019-08-01", "2019-09-01",
                   "2019-10-01", "2019-11-01", "2019-12-01")),
        labels = c("Jan", "Feb", "Mar", "Apr", "May", "Jun",
                   "Jul", "Aug", "Sep", "Oct", "Nov", "Dec")) + 
    ylab("Number of Recoded Rides") +
    scale_y_continuous(labels = scales::comma) +
    ggtitle("Number of Total Rides per Day")
```

Here we can see that the ridership increases a lot in the summer months. The warmer weather and road conditions may be more conducive to biking. However, there seems to be large fluctuations throughout the dataset. This may be weekday and weekend usage. Let's also look at a smoother version, just to make it easier on our poor eyes.

```{R Smoothed}
# Plot the smoothed lineplot
ggplot(data = longer, aes(x = date, y = daily_rides)) +
    geom_smooth(aes(color = usertype)) +
    scale_color_manual(
            name = "User Type",
            labels = c("Customer", "Subscriber", "Total"),
            values = c("#F8766D", "#619CFF", "#000000")) +
    xlab("Ride Start Date") +
    scale_x_continuous(
        breaks = as.Date(
                 c("2019-01-01", "2019-02-01", "2019-03-01",
                   "2019-04-01", "2019-05-01", "2019-06-01",
                   "2019-07-01", "2019-08-01", "2019-09-01",
                   "2019-10-01", "2019-11-01", "2019-12-01")),
        labels = c("Jan", "Feb", "Mar", "Apr", "May", "Jun",
                   "Jul", "Aug", "Sep", "Oct", "Nov", "Dec")) + 
    ylab("Number of Recoded Rides") +
    scale_y_continuous(labels = scales::comma) +
    ggtitle("Number of Total Rides per Day (Smoothed)")
```

**We can see that ridership peaks around the month of August**

If there were no other influencing factors on the data, the graph should end the year around the same place it started. However, COVID-19 was happening and things like bike-sharing and going out without protection became more difficult (likely leading to the sharper drop at the end of the year).

### Weekly
First, the data needs to be rewritten so that each date is turned into a corresponding day of the week. Thankfully, R makes quick work of that...

```{R Weekdays}
# Include a 'factor()' function to customize the order of the dates
full_2019$weekday <- weekdays(full_2019$start_date) %>%
    factor(levels = c("Sunday", "Monday", "Tuesday", "Wednesday", "Thursday", "Friday",
        "Saturday"))
```

Then the annual rides need to be displayed by day of the week. I can also try to look at ridership on specific days (like holidays) to see what the service is being used for.

```{R Weekly Barplot}
# Plot a barplot of rides split by day of the week
ggplot(data = full_2019) +
    geom_bar(mapping = aes(x = weekday),
    fill = c("#333333", "#808080",  "#808080",  "#808080", 
             "#808080",  "#808080", "#333333")) +
    xlab("Day of the Week") +
    ylab("Number of Rides") +
    scale_y_continuous(labels = scales::comma) +
    ggtitle("Number of Rides Each Day of the Week")
```

Manually showing the weekend values as a darker shade highlights that the ridership on the weekends is lower than the weekdays. It is possible some people are using the service to commute but there are still many rides happening on the weekends.

### Foolin Around
The average number of rides taken daily is:
```{R Daily Average}
# Find the average
# (Might not be applicable if data is not normally distributed)
mean(date_grouped$daily_rides)
```

The minimum and maximum number of rides on any given day was:
```{R MinMax}
# Find the min and max
min(date_grouped$daily_rides)
max(date_grouped$daily_rides)
```

The maximum occurred on 
```{R Max Date}
# find the date that had the single most rides of any day
biggest <- date_grouped %>%
    filter(daily_rides == max(daily_rides))
biggest$start_date
```

The minimum occurred on
```{R Min Date}
# Find the date that had the fewest rides
smallest <- date_grouped %>%
    filter(daily_rides == min(daily_rides))
smallest$start_date
```

But, just to be sure, a histogram of the daily counts should be examined as well.

```{R Daily Rides Histogram}
# Plot a histogram of the number of rides recorded for each day
ggplot(data = date_grouped) +
    geom_histogram(mapping = aes(x = daily_rides),
    color = "black", fill = "#582a87", binwidth = 800, center=400) +
    xlab("Number of Daily Rides") +
    ylab("Number of Days With Each Ride Count") +
    ggtitle("Histogram of the Number of Days with Each Ride Count") +
    scale_x_continuous(labels = scales::comma)
```

Clearly, the data is bimodal. Perhaps a breakdown by day of the week?

```{R Histogram Facet}
# Order the days of the week in the date_grouped dataset
date_grouped$day_of_week <- weekdays(date_grouped$start_date) %>%
    factor(levels = c("Sunday", "Monday", "Tuesday", "Wednesday", "Thursday", "Friday", "Saturday"))

# Plot the facet graph for each day of the week
ggplot(data = date_grouped) +
    geom_histogram(mapping = aes(x = daily_rides, fill = day_of_week), color = "black", bins = 15L) +
    facet_wrap(~day_of_week) +
    xlab("Number of Daily Rides (Thousands)") +
    scale_x_continuous(
        breaks = c(0, 5000, 10000, 15000, 20000),
        labels = c(0, 5, 10, 15, 20)) +
    ylab("Number of Days With Each Ride Count") +
    labs(fill = "Day of the Week") +
    ggtitle("Number of Days with Each Ride Count",
        subtitle = "Facet Histogram Split by Day of the Week")
```

Nope. Hmmm. Perhaps it's a seasonal thing. Let's see how I can make that happen...

### Seasonal

```{R By Season}
# First, make a season column
date_grouped$season <- ifelse(date_grouped$start_date < "2019-03-20", "Winter",
    ifelse(date_grouped$start_date < "2019-06-21", "Spring",
    ifelse(date_grouped$start_date < "2019-09-23", "Summer",
    ifelse(date_grouped$start_date < "2019-12-21", "Autumn", "Winter")))) %>%
    factor(levels = c("Winter", "Spring", "Summer", "Autumn"))

# Then use the facets to make histograms split by season
ggplot(data = date_grouped) +
    geom_histogram(mapping = aes(x = daily_rides, fill = season),
        color = "black", binwidth = 800, center = 400) +
    facet_wrap(~season) +
    scale_fill_manual(values = c("#00ccff", "#00b300", "#ffff00", "#ff6600")) +
    xlab("Number of Daily Rides") +
    ylab("Number of Days With Each Ride Count") +
    labs(fill = "Season") + 
    scale_x_continuous(labels = scales::comma)
```

Ahhhhhh, yes. Here we can see the back and forth sway of the number of daily rides. As the seasons become warmer, the nummber of rides tends to increase. As the temperature drops, daily bike rides become less frequent. This, at least, makes sense.

Using this information, the sensible thing to do is to show basic summaries for the seasons, to predict ridership for each season. This could also be broken apart monthly.
```{R By month}
# Again, make a new column
date_grouped$month <- date_grouped$start_date %>%
    month()

# And turn that into a histogram (12 bins each)
ggplot(data = date_grouped) +
    geom_histogram(mapping = aes(x = daily_rides, fill = month), color = "black", bins = 12L) +
    facet_wrap(~month) +
    scale_x_continuous(
        breaks = c(0, 5000, 10000, 15000, 20000, 25000),
        labels = c(0, 5, 10, 15, 20, 25)) +
        xlab("Number of Daily Rides (Thousands)") +
        ylab("Number of Days with Each Count") +
        labs(fill = "Month") +
        ggtitle("Histogram of Number of Days with Each Daily Ride Count",
                subtitle = "Facet Histogram Split by Month")
```

While it might be useful, this data is probably easier to work with seasonally:

```{R}
# Find the average number of rides per day each season
season_average <-date_grouped %>%
    group_by(season) %>%
    summarize(average_daily = mean(daily_rides))
season_average
```


## Daily Behavior
It is important for us to see the daily usage of the bikes. That way, we can make inferences about what the major purpose of the bikes are for the users.

```{R Daily Histogram}
#Create a new column changing the time into a number of seconds that can be put in histogram bins
full_2019$seconds_time <- as.numeric(hm(substr(full_2019$start_time, 12, 16)))

# Construct a histogram of the times each ride occurred each day
ggplot(data = full_2019) +
    geom_histogram(mapping = aes(x = seconds_time),
    binwidth = 1800, center = 900, color = "black", fill = "#582a87") +
    annotate("text", x = 30000, y = 170000, label = "8-8:30am", size = 5) +
    annotate("text", x = 62500, y = 270000, label = "5-5:30pm", size = 5) +
    scale_x_continuous(
        breaks = c(0, 3600, 7200, 10800, 14400, 18000,
                21600, 25200, 28800, 32400, 36000, 39600,
                43200, 46800, 50400, 54000, 57600, 61200,
                64800, 68400, 72000, 75600, 79200, 82800, 86400),
        labels = c("12AM", 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, "12PM", 1,
                    2, 3, 4, 5, 6, 7, 8, 9, 10, 11, "12AM")) +
    xlab("Time") +
    ylab("Number of Recoded Rides") +
    scale_y_continuous(labels = scales::comma) +
    ggtitle("The Number of Recorded Rides Every Half Hour", subtitle = "Total Across the Year")
```

The function "as.numeric(hm(substr(full_2019$start_time, 12, 16)))" takes the substring of the date time "hh:mm" and converts it into a numerical count of the seconds. Then the bins are constructed so that the first bin starts at 0000 seconds (00:00) and ends at 1800 seconds (00:30), ensuring that each bin spans 30 minutes in total.

Here, we can see that the bikes were most commonly used at paek times throughout the day that correspond to commuting to and from work. However, that pattern is changed when the data is divided between the user type.

```{R Divided Histogram}
# Plot histograms of ride times split by user type
ggplot(data = full_2019) +
    geom_histogram(mapping = aes(x = seconds_time, fill = usertype),
    binwidth = 1800, center = 900, color = "black") +
    facet_wrap(~usertype) + 
    scale_x_continuous(
        breaks = c(0, 14400, 28800, 43200, 57600, 72000, 86400),
        labels = c("12AM", 4, 8, "12PM", 4, 8, "12AM")) +
    xlab("Time") +
    ylab("Number of Recorded Rides") +
    labs(fill = "User Type") +
    scale_y_continuous(labels = scales::comma) +
    ggtitle("The Number of Recorded Rides Every Half Hour",
        subtitle = "Total Across the Year Split by User Type")
```

Interestingly, dividing the data by usertype reveals that casual riders, while more likely to use the service during the day (specifically in the afternoon), do not have any particularly stand-out times of use.
The annual subscribers, on the other hand, tend to use the service a ton during peak commuting hours. This suggests that annual riders are using the service to commute more than casual riders.

## Trip Durations
Lastly, I want to take a closer look at the trip durations. First, see if there are any "funny" values...

```{R Trip Durations}
# Find the min and max durations
max(full_2019$tripduration)
min(full_2019$tripduration)
```

Oh dear, 61 seconds is a mere minute, but not short enough to remove. However, the max is 10,628,400 seconds, which is just over 123 days long! After trying a few values, I feel I can see a decent histogram showing rides 2 hours or less. This excludes 42,533 rides that were longer than 2 hours and leaves 3,775,471 that are 2 hours or less.
```{R Filtered Max}
# Filter the data to <= 2 hours
filtered_trip <- full_2019 %>%
    filter(tripduration <= 7200)

# Plot histogram of trip durations
ggplot(data = filtered_trip) +
    geom_histogram(mapping = aes(x = tripduration), fill = "#582a87",
    binwidth = 180, center = 90, color = 'black') +
    xlab("Trip Duration (HH:MM)") +
    scale_x_continuous(
        breaks = c(0, 900, 1800, 2700, 3600, 4500, 5400, 6300, 7200),
        labels = c("00:00", "00:15", "00:30", "00:45", "01:00", "01:15", "01:30", "01:45", "02:00")) +
    ylab("Counts for Each Time") +
    scale_y_continuous(labels = scales::comma) +
    ggtitle("Number of Rides for Each Duration")
```

Naturally, we also want to see the breakdown of the data by user type:
```{R Time User Type Histogram}
# Plot histogram of trip durations split by user type
ggplot(data = filtered_trip) +
    geom_histogram(mapping = aes(x = tripduration, fill = usertype),
        binwidth = 180, center = 90, color = 'black') +
    labs(fill = "User Type") +
    xlab("Trip Duration (HH:MM)") +
    scale_x_continuous(
        breaks = c(0, 1800, 3600, 5400, 7200),
        labels = c("00:00", "00:30", "01:00", "01:30", "02:00")) +
    ylab("Counts for Each Time") +
    facet_wrap(~usertype) +
    scale_y_continuous(labels = scales::comma) +
    ggtitle("Number of Rides for Each Duration",
            subtitle = "Histogram Split by User Type")
```

It may be hard to see the data side-by-side like this, so a boxplot of the data can also be made.
```{R Trip Boxplot}
# Plot
ggplot(data = filtered_trip, aes(x = usertype, y = tripduration, fill = usertype)) + 
    stat_boxplot(geom = "errorbar", width = 0.2) +
    geom_boxplot() +
    ylab("Trip Duration (HH:MM)") +
    scale_y_continuous(
        breaks = c(0, 600, 1200, 1800, 2400, 3000, 3600, 4200, 4800, 5400, 6000, 6600, 7200),
        labels = c("00:00", "00:10", "00:20", "00:30", "00:40", "00:50", "01:00",
                    "01:10", "01:20", "01:30", "01:40", "01:50", "02:00")) +
    xlab("User Type") +
    labs(fill = "User Type") +
    ggtitle("Boxplots of Trip Duration Split by User Type")
```

Here, we can see that while there are many more rides made by subscribers, the trip duration is a lot shorter with a lot less variability. This suggests that the casual rider is in less of a hurry or that they have a longer distance to travel. The summary statistics can provide us with more information:
```{R Summary Statistics}
# Summary of Customer
summary(filtered_trip$tripduration[filtered_trip$usertype == "Customer"])

# Summary of Subscriber
summary(filtered_trip$tripduration[filtered_trip$usertype == "Subscriber"])
```

Here, we can see that the median ride length for the subscriber is 587 seconds (just under 10 minutes), the median trip for a customer is 1492 seconds (almost 25 minutes).

## Findings

Overall, the data show a convincing narrative. There are two types of users

1. Customer
2. Subscriber

Subscribers are people who have purchased an annual pass. While thier rides tend not to last as long as a "Customer" (casual) ride, they make up nearly 75% of the total number of rides.
Also, while casual riders tend to use the service during the day with no discernable patterns, membership users tend to use the sevice to commute (and throughout the day).
The casual riders and the Subscribers tend to be about the same age, but there are significantly more men using the service than women.
The rides tend to take place during the summer months. The outside temperature and road conditions likely factors in to people's decisions to use a bike-share.


## Recommendations
There are three main recommendations from the data:

1. Encourage more women to be able to use the service.
2. Encourage people to use the service as a means for commuting (especially over short distances).
3. Make the most out of the summer months and provide incentives for encouraging rides during the off season, provided the conditions are safe.

> Encourage more women to be able to use the service.

Perhaps looking into making the bikes more comfortable to sit on as well as programs to help women. Perhaps advertising directly focused on appealing to women with an emphasis on using the bike for commuting, especially in the city.

> Encourage people to use the service as a means for commuting.

Members use this service to commute a lot more than their casual counterparts. If there is a desire to get more members to use the service, focus should be placed on how the service is great for commuting.
Centralized hubs for bikes should be commonplace throughout the city. Perhaps even letting members have exclusive access to a company bike.
This sevice is also something that should be addressed at the government level, pushing for legislation that allows more/better bike infrastructure, routes, and incentives.
This can also be done at the business level, providing companies in the city a program to allow employees on their payroll to be able to use the service at a reduced/no cost.
Making sure that the bikes also have storage space for some groceries may also help people who live nearby to be able to also use the service to run errands.

> Make the most out of the summer months.

The bussiest individual days are found in the summer. However, there are still people using the service in the winter. While controlling the teamperature outside is difficult, adding comfort options to imporve ride quality could be looked into.
For example, making the handlebar marerial something that does not conduct heat well to help keep hands warmer in the winter (or even using the energy from the wheels to warm the handlebars).
Providing extra incentives for people to purchase the annual passes in the summer. They might not use it all year, but they are more likely to once it gets warmer.

Thanks for sticking this one through! Let me know what improvements can be made.

Quintin Ramsey